Edit docs for config templating
quickwit-oss/quickwit pull request #1841
Opened 2022-08-10 08:59 UTC by boraarslan

2022-08-10 09:03 UTC, boraarslan commented
Should we change the tutorial to use only the templating for config? I only added it as an alternative for now, but I believe it is more ergonomic to use templating instead of writing from stdout.

2022-08-10 14:48 UTC, guilload requested changes

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +## Templating
```suggestion
## Using environment variables in the configuration
```

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +It is possible to pass environment variables to config:
```suggestion
You can use environment variable references in the config file to set values that need to be configurable during deployment. To do this, use:

${VAR_NAME}

Where  `VAR_NAME` is the name of the environment variable.

Each variable reference is replaced at startup by the value of the environment variable. The replacement is case-sensitive and occurs before the configuration file is parsed. References to undefined variables throw an error unless you specify a default value or custom error text.

To specify a default value, use:

${VAR_NAME:-default_value}

Where `default_value` is the value to use if the environment variable is not set.
```

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +Will get interpreted by Quickwit as:
```suggestion
Will be interpreted by Quickwit as:
```

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +rest_listen_port: 4444 #< 1111 if QW_LISTEN_PORT is not set
Let's just not export `QW_LISTEN_PORT` and render with the default value `1111`. There's already an example with `QW_LISTEN_ADDRESS`

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +<config_field>: ${<ENV_VAR_NAME>}
```suggestion
<config_field>: ${VAR_NAME}
```

2022-08-10 14:48 UTC, guilload commented on docs/configuration/node-config.md
> +<config_field>: ${<ENV_VAR_NAME>:-<default value>}
```suggestion
<config_field>: ${VAR_NAME:-default_value}
```

2022-08-10 14:48 UTC, guilload commented on docs/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3.md
> +> You can also pass environment variables directly:
I think this tutorial deserves some rewriting. I'll take care of it before the next release. You can dismiss those changes for now.

2022-08-11 14:52 UTC, guilload approved these changes

2022-08-12 11:38 UTC, merged