add support for forcing commit or waiting for a commit on file ingest…
quickwit-oss/quickwit pull request #3049
Opened 2023-03-18 10:53 UTC by trinity-1686a

### Description

add command line arguments to wait for/force a commit when ingesting from the cli

### How was this PR tested?

not tested yet, will do on monday

2023-03-29 20:02 UTC, fmassot commented on quickwit/quickwit-cli/src/index.rs
> +                        .help("Enable waiting after the last document is sent")
`after the last document is sent`

sent to who?

2023-03-29 20:26 UTC, fmassot commented on quickwit/quickwit-rest-client/src/rest_client.rs
> +                            &format!("{ingest_path}?{query_param}"),
you should use the `query_string` argument that is used for passing your query parameters.

2023-03-29 20:30 UTC, fmassot commented on quickwit/quickwit-rest-client/src/rest_client.rs
> +                            &format!("{ingest_path}?{query_param}"),
I would simplify the code like this:

```rust

let query_params = if !batch_reader.has_next() {
    last_block_commit.to_query_parameter()
};
self.transport.send::<()>...
```

2023-03-29 20:32 UTC, fmassot requested changes
See comments.

2023-04-01 05:59 UTC, imotov commented on quickwit/quickwit-cli/src/index.rs
> +            (true, true) => bail!("Can't specify both --wait and --force"),
You can probably bail out even earlier during command line parsing by using ArgGroup or the conflicts_with method.

2023-04-01 05:59 UTC, imotov commented on quickwit/quickwit-cli/src/index.rs
> +                        .help("Wait for a document to be commited before exiting")
Maybe "Wait for all documents to be committed and available for search before exiting"?

2023-04-02 12:22 UTC, fmassot commented on quickwit/quickwit-cli/src/index.rs
> +                        .help("Force a commit after the last document is sent, and wait for all documents to be commited .nd available before exiting")
```suggestion
                        .help("Force a commit after the last document is sent, and wait for all documents to be committed and available for search before exiting")
```

2023-04-02 12:25 UTC, fmassot approved these changes
Just one little typo to fix and we are good with the PR!

2023-04-03 12:03 UTC, merged