[WIP] Update deps.
quickwit-oss/quickwit pull request #3245
Opened 2023-04-30 13:34 UTC by saroh

- [ ] remove time dependency from `chrono` (opt out of `oldtime` feature)
- [ ] remove dependency on `datadog-grok` (opt out of `parse_grok(s)` features)
- [ ] depend on last release version of `vrl-compiler/stdlib`
- [ ] remove unused deps (`cargo +nightly udeps`)
- [ ] upgrade deps

### Description

Refs #2878 

### How was this PR tested?

UTs.

2023-04-30 17:22 UTC, guilload commented
AWESOME!

Two questions:
- What functions depend on the `wasmbind` chrono feature?
- How hard would it be to automate the upgrade and remove unused deps process?

2023-04-30 17:23 UTC, guilload approved these changes

2023-05-01 01:16 UTC, fulmicoton commented on quickwit/Cargo.toml
>  clap = { version = "=3.1", features = ["env"] }
do we actually use wasmbind?

2023-05-01 01:18 UTC, fulmicoton commented on quickwit/Cargo.toml
> +dialoguer = "0.10.4"
that's not useful...

It is a bit counterintuitive, but 
```dialoguer = "0.10.4"```

actually means any version greater than 0.10.4  and compatible with semver.

We can keep 0.10.4 and just delete refresh `Cargo.lock`.

2023-05-01 01:22 UTC, fulmicoton requested changes
Most of the version updates in this PR are not very useful.
Can you revert those and keep the good stuff in?
(VRL update, default-features = false)


Copy pasting my inner comment:

It is a bit counterintuitive, but
dialoguer = "0.10.3"

actually means any version greater than 0.10.4 and compatible with semver.

We can keep 0.10.4 and just delete refresh Cargo.lock.

Keeping it low has some virtue.
If one deps depends on "=0.10.3", (contrived example of course), then that Cargo will do the right thing and stick to 0.10.3 to avoid having two versions of the same package.

2023-05-01 11:57 UTC, saroh commented
> How hard would it be to automate the upgrade and remove unused deps process?

THe upgrade is easy but seeing the other comments it's not necessary here :) 
The remove is harder: it has false positives and for instance in our case there's one caught by clippy in `quickwit-metadata`

2023-05-01 14:37 UTC, guilload commented
At one point, we were only depending on minor versions, i.e. `x.y` instead of `x.y.z`. Should we revert back to that practice?

2023-05-08 03:13 UTC, fulmicoton commented
@guilload. That practise was due to me being ignorant.

crate = "x.y.z" actually is interpreted as 
pick anything semver compatible and greater than "x.y.z".
If possible pick the latest one.

This is exactly what we want.

Using a ".z" is a good practise, because let's say you are using a crate today and test it over 4.1.4.
You only know that it works on 4.1.4, and nothing tells you it is compatible with 4.1.3.

For instance, you might be using a function that did not exist in 4.1.3.

2023-05-08 03:15 UTC, fulmicoton approved these changes

2023-05-08 03:15 UTC, fulmicoton commented
@saroh awesome job!

2023-05-08 03:43 UTC, merged