Some sanity rewrite of the LocalSplitStore
quickwit-oss/quickwit pull request #4275
Opened 2023-12-14 03:26 UTC by fulmicoton

- Renaming  `LocalSplitStore` -> `IndexingSplitCache`.
- Removing of the useless BinaryHeap, HashMap, using instead a single BTreeMap
- Isolating quota and BTreeMap to ensure their transactionality.
- Logging eventual io errors.

2023-12-14 03:28 UTC, fulmicoton commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +    split_store_quota: SplitStoreQuota,
I moved the non io stuff to this `struct` to make it easier to proofread that we cannot reach an inconsistent state.

2023-12-14 03:28 UTC, fulmicoton commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +
at this point in the method the split registry and the directory content is inconsistent.

2023-12-14 12:42 UTC, fmassot commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +/// if the cache is NOT under pressure but some splits are actually useless.
the sentence seems incomplete

2024-06-13 09:40 UTC, trinity-1686a requested changes

2024-06-13 09:40 UTC, trinity-1686a commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +        self.split_store_quota.add_split(split_folder.num_bytes);
i think we want to add to quota only if there wasn't already a matching split

2024-06-13 09:40 UTC, trinity-1686a commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +                if let Err(io_err) = tokio::fs::remove_dir(&from_path).await {
this only remove empty directories, it's unlikely to actually succeed

2024-06-13 09:40 UTC, trinity-1686a commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
>              self.evict_one_split().await?;
do we prevent `max_num_splits = 0` and `max_num_bytes` isn't somewhere? If not, this can panic

2024-06-13 09:40 UTC, trinity-1686a commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +        if !self.split_registry.remove(split_id) {
i'm not sure about the semantic on the error path. We forget we have the split, remove it from quota, but leave it on disk.
I think checking if the split is known, trying to move it, and then remove from the registry might be better, but am not 100% sure.

2024-06-13 09:40 UTC, trinity-1686a commented on quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
> +        let evicted_split = self
same wrt to semantic on the error path

2025-01-08 15:47 UTC, closed without merging