update tantivy
quickwit-oss/quickwit pull request #4745
Opened 2024-03-15 07:05 UTC by PSeitz

### Description

Describe the proposed changes made in this PR.

### How was this PR tested?

Describe how you tested this PR.

2024-03-15 07:33 UTC, fulmicoton approved these changes

2024-03-15 07:34 UTC, fulmicoton requested changes
Can you check the regression in the rest integration tests?

2024-03-15 07:48 UTC, PSeitz commented
> Can you check the regression in the rest integration tests?

It's not a regression, the result order is a little bit flaky. I'll fix it

2024-03-16 04:45 UTC, fulmicoton approved these changes

2024-03-16 07:17 UTC, merged