wildcard casing
quickwit-oss/quickwit pull request #5251
Opened 2024-07-24 07:37 UTC by trinity-1686a

fix normalizer used for the `raw_lowercase` tokenanizer

2024-07-24 07:39 UTC, trinity-1686a commented on quickwit/quickwit-query/src/tokenizers/tokenizer_manager.rs
> +            RAW_LOWERCASE_TOKENIZER_NAME
the tokenizer here isn't really supposed to generate multiple tokens

2024-07-24 07:39 UTC, trinity-1686a commented on quickwit/quickwit-search/src/root.rs
> +            .term_ranges_grouped_by_field
range queries (including wildcards) were not properly counted

2024-07-25 09:33 UTC, fulmicoton commented
Can we have a unit test somewhere?

2024-07-25 09:34 UTC, fulmicoton requested changes
Please add a unit test. If it is difficult, an integration test will do.
Make sure it runs on elasticsearch if you go for the integration test.

2024-07-29 02:45 UTC, fulmicoton approved these changes

2024-07-29 02:47 UTC, merged